### ISSUE TITLE
Use CRAN task views

### ISSUE THREAD

**Issue by nuest** [achubaty/rocker-files#2]
IMHO the CRAN task view maintainers do a great job on presenting the available package on a specific topic. Would you consider switching to installing the `Spatial` and `SpatioTemporal` task views with the package `ctv` instead of selected packages?

**Comment by achubaty** [comment]
It's an interesting idea, but I'm not sure I want to implement it for the reasons below.
1. How often do the task view packages change? The _Spatial_ and _Spatiotemporal_ task views in `ctv` haven't been updated since 2014-12-18, which is a problem for item 4 below. Too frequent task view changes are also an issue with item 2 below.
2. How to easily ensure that system dependencies are met, without doing so manually?
3. There are A LOT of packages in these taskviews (many more than most people actually need), so I'm worried about bloat. Maybe only installing the 'core' packages of these task views is needed, but see item 5.
4. Several packages aren't available for the the current version of R (3.3.1), including `gstudio`, `ncdf`, `RPyGeo`, `UScensus2000blkgrp`. Packages like `ncdf` have been superceded (by `ncdf4`) yet are still included in the task view for (I'm assuming) historical reasons. I don't want to have to sort through this list in order to maintain a package 'blacklist'. As mentioned in item 3, installing only the core packages would solve this problem.
5. There are packages I've included in my _r-spatial-base_ image that aren't included in the task views.
6. Using the `ctv` package to programatically get package names adds a layer of obfuscation to the Dockerfile because the individual packages are not listed explicitly. I could be convinced to add these packages explicitly though.

It's easy enough (at least for the core packages) to create your own image based on my `r-spatial-base` image that adds the missing packages. Just add the following R code to your Dockerfile:

``` r
install.packages("ctv")
library("ctv")

## for core 'Spatial' taskview packages
ctv.spatial <- read.ctv(system.file("ctv", "Spatial.ctv", package = "ctv"))
pkgs1 <- ctv.spatial$packagelist[ctv.spatial$packagelist$core == TRUE,]$name
do.call(install.packages, list(pkgs1))

## for core 'SpatioTemporal' taskview packages
ctv.spatiotemporal <- read.ctv(system.file("ctv", "SpatioTemporal.ctv", package = "ctv"))
pkgs2 <- ctv.spatiotemporal$packagelist[ctv.spatiotemporal$packagelist$core == TRUE,]$name
do.call(install.packages, list(pkgs2))
```
